name: Comment

on:
  issue_comment:
    types:
      - created

jobs:
  publish:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/publish')
    name: Publish With Target
    steps:
      - name: Dispatch
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GH_WEB_PACKAGES_TOKEN }}
          script: |
            const issueNumber = context.issue.number
            await github.actions.createWorkflowDispatch({
              ...context.repo,
              workflow_id: 'release-pr.yml',
              ref: context.ref,
              inputs: {
                pr_number: `${issueNumber}`,
              },
            })

  deploy-storybook:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/deploy-storybook')
    name: Publish With Target
    steps:
      - name: Dispatch
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GH_WEB_PACKAGES_TOKEN }}
          script: |
            const issueNumber = context.issue.number
            await github.actions.createWorkflowDispatch({
              ...context.repo,
              workflow_id: 'deploy-pr.yml',
              ref: context.ref,
              inputs: {
                pr_number: `${issueNumber}`,
              },
            })
